[workspace]
resolver = "2"

members = [
    "protocol",
    "server",
    "client",
    "helpers",
    "example/chat-server",
    "example/chat-cli",
    "example/chat-client",
    "example/chat-protocol",
    "example/chat-tests",
]
