[package]
name = "chat-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
multiplayer-kit-helpers = { path = "../../helpers", default-features = false }
multiplayer-kit-protocol = { path = "../../protocol" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = "1"
